module.exports = utils = {
    paths: {
        arrayToObject: "./src/arrayToObject.ts",
        capitalize: "./src/capitalize.ts",
        checkStringLength: "./src/checkStringLength.ts",
        clearTime: "./src/clearTime.ts",
        cookieStorage: "./src/cookieStorage.ts",
        dateDiff: "./src/dateDiff.ts",
        deepCopy: "./src/deepCopy.ts",
        formatDate: "./src/formatDate.ts",
        formValidator: "./src/formValidator.ts",
        getBrowserName: "./src/getBrowserName.ts",
        getBrowserVersion: "./src/getBrowserVersion.ts",
        isBrowserChrome: "./src/isBrowserChrome.ts",
        isBrowserEdge: "./src/isBrowserEdge.ts",
        isBrowserFirefox: "./src/isBrowserFirefox.ts",
        isBrowserIE: "./src/isBrowserIE.ts",
        isBrowserOpera: "./src/isBrowserOpera.ts",
        isBrowserSafari: "./src/isBrowserSafari.ts",
        isDateAfter: "./src/isDateAfter.ts",
        isEmail: "./src/isEmail.ts",
        isEmpty: "./src/isEmpty.ts",
        isPhoneNumber: "./src/isPhoneNumber.ts",
        isSameDate: "./src/isSameDate.ts",
        isSameObject: "./src/isSameObject.ts",
        isStrongPassword: "./src/isStrongPassword.ts",
        logger: "./src/logger.ts",
        modifyDate: "./src/modifyDate.ts",
        randomId: "./src/randomId.ts",
        storageManagement: "./src/storageManagement.ts",
        stringInsert: "./src/stringInsert.ts",
        toggleBodyOverflow: "./src/toggleBodyOverflow.ts",
    }
}
