module.exports = utils = {
    paths: {
        arrayToObject: "./src/arrayToObject/index.ts",
        capitalize: "./src/capitalize/index.ts",
        checkStringLength: "./src/checkStringLength/index.ts",
        clearTime: "./src/clearTime/index.ts",
        CookieStorage: "./src/CookieStorage/index.ts",
        dateDiff: "./src/dateDiff/index.ts",
        deepCopy: "./src/deepCopy/index.ts",
        formatDate: "./src/formatDate/index.ts",
        FormValidator: "./src/FormValidator/index.ts",
        getBrowserName: "./src/getBrowserName/index.ts",
        getBrowserVersion: "./src/getBrowserVersion/index.ts",
        isBrowserChrome: "./src/isBrowserChrome/index.ts",
        isBrowserEdge: "./src/isBrowserEdge/index.ts",
        isBrowserFirefox: "./src/isBrowserFirefox/index.ts",
        isBrowserIE: "./src/isBrowserIE/index.ts",
        isBrowserOpera: "./src/isBrowserOpera/index.ts",
        isBrowserSafari: "./src/isBrowserSafari/index.ts",
        isDateAfter: "./src/isDateAfter/index.ts",
        isEmail: "./src/isEmail/index.ts",
        isEmpty: "./src/isEmpty/index.ts",
        isPhoneNumber: "./src/isPhoneNumber/index.ts",
        isSameDate: "./src/isSameDate/index.ts",
        isSameObject: "./src/isSameObject/index.ts",
        isStrongPassword: "./src/isStrongPassword/index.ts",
        modifyDate: "./src/modifyDate/index.ts",
        randomId: "./src/randomId/index.ts",
        StorageManagement: "./src/StorageManagement/index.ts",
        stringInsert: "./src/stringInsert/index.ts",
        toggleBodyOverflow: "./src/toggleBodyOverflow/index.ts",
    },
    indexes: [
        { from: "./src/arrayToObject/index.ts", to: "./arrayToObject/index.js", },
        { from: "./src/capitalize/index.ts", to: "./capitalize/index.js", },
        { from: "./src/checkStringLength/index.ts", to: "./checkStringLength/index.js", },
        { from: "./src/clearTime/index.ts", to: "./clearTime/index.js", },
        { from: "./src/CookieStorage/index.ts", to: "./CookieStorage/index.js", },
        { from: "./src/dateDiff/index.ts", to: "./dateDiff/index.js", },
        { from: "./src/deepCopy/index.ts", to: "./deepCopy/index.js", },
        { from: "./src/formatDate/index.ts", to: "./formatDate/index.js", },
        { from: "./src/FormValidator/index.ts", to: "./FormValidator/index.js", },
        { from: "./src/getBrowserName/index.ts", to: "./getBrowserName/index.js", },
        { from: "./src/getBrowserVersion/index.ts", to: "./getBrowserVersion/index.js", },
        { from: "./src/isBrowserChrome/index.ts", to: "./isBrowserChrome/index.js", },
        { from: "./src/isBrowserEdge/index.ts", to: "./isBrowserEdge/index.js", },
        { from: "./src/isBrowserFirefox/index.ts", to: "./isBrowserFirefox/index.js", },
        { from: "./src/isBrowserIE/index.ts", to: "./isBrowserIE/index.js", },
        { from: "./src/isBrowserOpera/index.ts", to: "./isBrowserOpera/index.js", },
        { from: "./src/isBrowserSafari/index.ts", to: "./isBrowserSafari/index.js", },
        { from: "./src/isDateAfter/index.ts", to: "./isDateAfter/index.js", },
        { from: "./src/isEmail/index.ts", to: "./isEmail/index.js", },
        { from: "./src/isEmpty/index.ts", to: "./isEmpty/index.js", },
        { from: "./src/isPhoneNumber/index.ts", to: "./isPhoneNumber/index.js", },
        { from: "./src/isSameDate/index.ts", to: "./isSameDate/index.js", },
        { from: "./src/isSameObject/index.ts", to: "./isSameObject/index.js", },
        { from: "./src/isStrongPassword/index.ts", to: "./isStrongPassword/index.js", },
        { from: "./src/modifyDate/index.ts", to: "./modifyDate/index.js", },
        { from: "./src/randomId/index.ts", to: "./randomId/index.js", },
        { from: "./src/StorageManagement/index.ts", to: "./StorageManagement/index.js", },
        { from: "./src/stringInsert/index.ts", to: "./stringInsert/index.js", },
        { from: "./src/toggleBodyOverflow/index.ts", to: "./toggleBodyOverflow/index.js", },
    ]
}
